# Generated by Django 5.0.2 on 2025-11-30 06:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('vision_id', models.BigIntegerField(blank=True, null=True)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.TextField(blank=True, null=True)),
                ('prev_hash', models.TextField(blank=True, null=True)),
                ('timeline_id', models.UUIDField(default=uuid.uuid4)),
                ('next_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_blocks', to='blocks.block')),
                ('prev_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_blocks', to='blocks.block')),
            ],
        ),
    ]
