# Generated by Django 5.0.2 on 2025-11-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('visions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='timeline_id',
        ),
        migrations.RemoveField(
            model_name='block',
            name='vision_id',
        ),
        migrations.AddField(
            model_name='block',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='visions.timeline'),
        ),
        migrations.AddField(
            model_name='block',
            name='vision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='visions.vision'),
        ),
    ]
