# Generated by Django 4.2.11 on 2025-12-06 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.TextField()),
                ('contact_name', models.TextField()),
                ('role', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(default='Med')),
                ('status', models.TextField(default='Active')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement', models.TextField(blank=True, null=True)),
                ('service', models.TextField(blank=True, null=True)),
                ('deal_stage', models.TextField()),
                ('probability_pct', models.IntegerField(default=0)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('deal_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retainer_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_frequency', models.TextField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True, null=True)),
                ('next_action_due', models.DateField(blank=True, null=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_action', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status_flags', models.JSONField(blank=True, default=list, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.contact')),
            ],
            options={
                'db_table': 'crm_deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.TextField(default='Med')),
                ('status', models.TextField(default='Pending')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_actions', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_actions', to='crm.deal')),
            ],
            options={
                'db_table': 'crm_next_actions',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.TextField()),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.TextField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact')),
            ],
            options={
                'db_table': 'crm_interactions',
                'ordering': ['-interaction_date'],
            },
        ),
    ]
