# Generated by Django 4.2.11 on 2025-12-06 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_user_id_deal_user_id_interaction_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='nextaction',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
    ]
