# Generated by Django 4.2.11 on 2025-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_user_id_alter_deal_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status_flags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
